### ISSUE TITLE
Stop event source on errors

### ISSUE THREAD

**Issue by noxone** [Hapag-Lloyd/oversigt#13]
If an event source throws too many errors, deactivate it automatically.

**Comment by noxone** [comment]
Or maybe throttle the execution time.

**Comment by noxone** [comment]
Event sources should be stopped by this commit: [96d3b194](https://github.com/Hapag-Lloyd/oversigt/commit/96d3b194f5ae3eb122b5191d900948cb952a2b86)

**Comment by lars-sh** [comment]
I don't get that code: You stop the event source on throwables that are not exceptions. It's that really the intention?

**Comment by noxone** [comment]
better like this?
