### ISSUE TITLE
Classpath scanning does not work with Java 10

### ISSUE THREAD

**Issue by noxone** [Hapag-Lloyd/oversigt#2]
**Symptoms**
Using a Java 10 JRE the classpath scanning does not work. The Google Guava code writes an error to the log and does not return any classes.
The log written is:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/C:/Users/micro/.m2/repository/com/google/inject/guice/4.1.0/guice-4.1.0.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

**Expected outcome**
Using Java 10 the classpath scan should result in the same classes found as using Java 8.

**How to replicate the problem**
Start commit 2512f1c9499fb4a3f33d3512a72f7dbb0cb9194d using a Java 10 JRE.

**Comment by noxone** [comment]
This seems to be addressed here https://github.com/google/guice/issues/1085 but a solution has not been found yet.

**Comment by SharpMan** [comment]
Where is the 'Type' Getter called from ?

**Comment by noxone** [comment]
It's not called directly from our code.
It is called while creating the Google Guice Injector after ``configure()`` has been called in our Module class. As it is called from within the Guice magic I cannot tell you the exact stack trace.

**Comment by GedMarc** [comment]
You can use a library https://github.com/classgraph/classgraph to classpath scan very efficiently for JRE 10 and 11

**Comment by lars-sh** [comment]
This seems to be fixed. At least... I can start and use Oversigt using JDK 15.
