### ISSUE TITLE
String.format parameter injection

### ISSUE THREAD

**Issue by lars-sh** [Hapag-Lloyd/oversigt#20]
At https://github.com/Hapag-Lloyd/oversigt/blob/6bf646b7f1ee1c4a60dfa4f1b0993f432304f8a4/core/src/main/java/com/hlag/oversigt/web/api/LoggingInterceptor.java#L65 "values" are injected into String.format, that is called later on.

**Comment by noxone** [comment]
Fixed by extracting the parameter values to another string format parameter
