### ISSUE TITLE
Nullness annotation refers to de.lars-sh package

### ISSUE THREAD

**Issue by noxone** [Hapag-Lloyd/oversigt#25]
Adding a `package-info.java` with the `@javax.annotation.ParametersAreNonnullByDefault` annotation does not remove the "default nullness" warning. Using the quickfix adds the annotation `@de.larssh.utils.annotations.NonNullByDefault` to the package info. 

@lars-sh: What's the reason behind that? What benefit do we have if we do not use the "standard" annotation?
Currently I would prefer to use the original `javax` annotation and to remove the warning if the javax annotation is present.

**Comment by lars-sh** [comment]
[`@ParametersAreNonnullByDefault`](https://static.javadoc.io/com.google.code.findbugs/jsr305/3.0.2/javax/annotation/ParametersAreNonnullByDefault.html) makes "the method parameters in that element are nonnull by default".

Instead [`@NonNullByDefault`](https://github.com/lars-sh/parent/blob/master/utils-annotations/src/main/java/de/larssh/utils/annotations/NonNullByDefault.java) handles "parameters, methods or fields" as it is based upon [`@DefaultAnnotation`](https://static.javadoc.io/com.github.spotbugs/spotbugs-annotations/3.1.12/edu/umd/cs/findbugs/annotations/DefaultAnnotation.html).

This might need to be described inside README.md or inside the JavaDoc of `@NonNullByDefault`. What do you think?
