### ISSUE TITLE
@ParametersAreNonnullByDefault and @Nullable seem to have no effect

### ISSUE THREAD

**Issue by noxone** [Hapag-Lloyd/oversigt#32]
If a package contains a package-info.java with the `@ParametersAreNonnullByDefault` annotation it doesn't force the parameters to be non null.

**Comment by lars-sh** [comment]
Remember to use [`@NonNullByDefault`](https://github.com/lars-sh/parent/blob/master/utils-annotations/src/main/java/de/larssh/utils/annotations/NonNullByDefault.java) as described at #25.
