### ISSUE TITLE
@Nullable for validation needs to use a non-spotbugs annotation

### ISSUE THREAD

**Issue by noxone** [Hapag-Lloyd/oversigt#47]
Maybe use this dependency: https://mvnrepository.com/artifact/com.github.spotbugs/spotbugs-annotations/3.1.12
or use the javax-annotation again so validation works

**Comment by noxone** [comment]
fixed

**Comment by lars-sh** [comment]
Related commit: https://github.com/Hapag-Lloyd/oversigt/commit/92cc1e0545dc86a0818be4c5164dd7a815f13966
